#!/usr/bin/env bash

if [ "$(uname)" = 'Darwin' ]; then
    osascript -e 'tell application "Finder" to eject (every disk whose ejectable is true and local volume is true)'
elif [ "$(uname)" = 'Linux' ]; then
    # This snippet was copied directly from 
    # [Christophe Vu-Brugier](https://stackoverflow.com/users/93414/christophe-vu-brugier)
    # from a [thread on stackoverflow](http://stackoverflow.com/a/19756542).

    for usb_dev in /dev/disk/by-id/usb-*; do
        dev=$(readlink -f $usb_dev)
        grep -q ^$dev /proc/mounts && umount $dev
    done
fi
